before_install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3
install: "true"
language: erlang
notifications:
  hipchat:
    - secure: "kTli2lyPoRjPOn1Ku39Oa+Mv2Tf/0gOei2mJkZfdHdZpcGH1nzoKmUe1Nhwk\nkzMB2XmgwF6PHm3nKpMuU72V6aWDoTEUASIgyqLRsZmqMWBs8pg3BvPg0NbR\nlm7tx4AVLq7CyESJV6XWqdhTAsQnNBCybBnbrtaWtV8jmUI2/HQ="
otp_release:
  - 19.2
  - 19.1
  - 19.0
  - 18.3
  - 18.2.1
  - 18.0
  - 17.5
  - 17.0
  - R16B03-1
  - R16B01
  - R15B03
env:
  - REBAR3=true
script: "make travis_ci"
